# Generated by Django 3.2 on 2021-06-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='PunchTable',
        ),
    ]
