# Generated by Django 3.2 on 2021-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0002_rename_board_punchtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedorder',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
