# Generated by Django 3.2 on 2021-06-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0003_alter_completedorder_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
