# Generated by Django 3.2 on 2021-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0004_auto_20210618_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepreview',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='filepreview',
            name='client_product_id',
        ),
        migrations.DeleteModel(
            name='FileTable',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='pdf_file',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.DeleteModel(
            name='FilePreview',
        ),
    ]
