# Generated by Django 3.2 on 2021-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0005_auto_20210618_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
