# Generated by Django 3.2 on 2021-06-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0006_alter_orderdetail_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedorder',
            name='order_date',
        ),
    ]
