# Generated by Django 3.2 on 2021-06-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0008_auto_20210621_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedOrder',
        ),
    ]
