# Generated by Django 3.2 on 2021-06-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0009_delete_completedorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='colors',
            new_name='product_colors',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='user_id',
        ),
    ]
