# Generated by Django 3.2 on 2021-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0010_auto_20210621_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], max_length=255, null=True),
        ),
    ]
