# Generated by Django 3.2 on 2021-06-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0011_alter_orderdetail_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancel_Order',
        ),
        migrations.RemoveField(
            model_name='pending_orders',
            name='client_name',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
