# Generated by Django 3.2 on 2021-06-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0012_auto_20210622_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='client_name',
        ),
    ]
