# Generated by Django 3.2 on 2021-06-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0013_remove_orderdetail_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproduct',
            name='client_code',
        ),
        migrations.RemoveField(
            model_name='logtable',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='board_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='build_location',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='client_product_id',
        ),
        migrations.RemoveField(
            model_name='pending_orders',
            name='client_product_id',
        ),
        migrations.RemoveField(
            model_name='punchtable',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='punchtable',
            name='client_product_id',
        ),
        migrations.RemoveField(
            model_name='punchtable',
            name='location',
        ),
        migrations.DeleteModel(
            name='ClientName',
        ),
        migrations.DeleteModel(
            name='ClientProduct',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LogTable',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='pending_orders',
        ),
        migrations.DeleteModel(
            name='PunchTable',
        ),
    ]
