# Generated by Django 3.2 on 2021-06-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0015_clientname_clientproduct_location_messages_orderdetail_pending_orders_punchtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='build_location',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='Laxmi.location'),
        ),
    ]
