# Generated by Django 3.2 on 2021-06-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0016_alter_orderdetail_build_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='build_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laxmi.location'),
        ),
    ]
