# Generated by Django 3.2 on 2021-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0017_alter_orderdetail_build_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Completed', 'Completed'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
    ]
