# Generated by Django 3.2 on 2021-06-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0018_alter_orderdetail_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='stock_count',
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(blank=True, choices=[('Punch Created', 'Punch Created'), ('Send Order', 'Send Order'), ('Punch in Progress', 'Punch in Progress'), ('Plate Positive in Progress', 'Plate Positive in Progress')], max_length=255, null=True),
        ),
    ]
