# Generated by Django 3.2 on 2021-06-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0019_auto_20210623_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
