# Generated by Django 3.2 on 2021-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0020_alter_messages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='seen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
