# Generated by Django 3.2 on 2021-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0021_alter_messages_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
