# Generated by Django 3.2 on 2021-06-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0024_notification_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='notify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laxmi.userprofileinfo'),
        ),
    ]
