# Generated by Django 3.2 on 2021-06-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0026_alter_userprofileinfo_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
