# Generated by Django 3.2 on 2021-06-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0029_messages_notify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='notify_user',
        ),
    ]
