# Generated by Django 3.2 on 2021-06-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0031_messages_notify_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Laxmi.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='notify_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
