# Generated by Django 3.2 on 2021-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0032_auto_20210624_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='subject',
            field=models.CharField(blank=True, choices=[('Punch Created', 'Punch Created'), ('Send Order', 'Send Order'), ('Punch in Progress', 'Punch in Progress'), ('Plate Positive in Progress', 'Plate Positive in Progress'), ('Notification From Admin', 'Notification From Admin')], max_length=255, null=True),
        ),
    ]
