# Generated by Django 3.2 on 2021-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0033_alter_messages_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='alert_date',
            new_name='plate_and_positive_alert_date',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='punch_alert_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
