# Generated by Django 3.2 on 2021-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laxmi', '0034_auto_20210624_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='color',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='plate_color',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('warning', 'warning'), ('danger', 'danger')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='punch_color',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('warning', 'warning'), ('danger', 'danger')], max_length=255, null=True),
        ),
    ]
